name: build-ubuntu20

on:
  workflow_dispatch:

jobs:
  build_linux_ubuntu20:
    runs-on: [self-hosted, ubuntu20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build linux amd64
        run: |
          flutter --version
          dart ./setup.dart linux --arch amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flclash-linux-ubuntu20-amd64
          path: |
            dist/**
            build/**
          if-no-files-found: warn
